//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/ServidorWCF")]
    public partial class Proveedor : object
    {
        
        private int IdField;
        
        private string CodigoField;
        
        private string NombreField;
        
        private string DireccionField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Almacen", Namespace="http://schemas.datacontract.org/2004/07/ServidorWCF")]
    public partial class Almacen : object
    {
        
        private int IdField;
        
        private string CodigoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/ServidorWCF")]
    public partial class Producto : object
    {
        
        private int IdField;
        
        private string CodigoField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private decimal PrecioVentaField;
        
        private int StockMinimoField;
        
        private int StockMaximoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal PrecioVenta
        {
            get
            {
                return this.PrecioVentaField;
            }
            set
            {
                this.PrecioVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int StockMinimo
        {
            get
            {
                return this.StockMinimoField;
            }
            set
            {
                this.StockMinimoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int StockMaximo
        {
            get
            {
                return this.StockMaximoField;
            }
            set
            {
                this.StockMaximoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemisionEntrada", Namespace="http://schemas.datacontract.org/2004/07/ServidorWCF")]
    public partial class RemisionEntrada : object
    {
        
        private int IdField;
        
        private string CodigoField;
        
        private System.DateTime FechaDocumentoField;
        
        private int IdProveedorField;
        
        private int IdAlmacenField;
        
        private int EstadoField;
        
        private ServiceReference1.RemisionEntradaDetalle[] ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaDocumento
        {
            get
            {
                return this.FechaDocumentoField;
            }
            set
            {
                this.FechaDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int IdProveedor
        {
            get
            {
                return this.IdProveedorField;
            }
            set
            {
                this.IdProveedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int IdAlmacen
        {
            get
            {
                return this.IdAlmacenField;
            }
            set
            {
                this.IdAlmacenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ServiceReference1.RemisionEntradaDetalle[] List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemisionEntradaDetalle", Namespace="http://schemas.datacontract.org/2004/07/ServidorWCF")]
    public partial class RemisionEntradaDetalle : object
    {
        
        private int IdField;
        
        private int IdRemisionEntradaField;
        
        private int IdProductoField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRemisionEntrada
        {
            get
            {
                return this.IdRemisionEntradaField;
            }
            set
            {
                this.IdRemisionEntradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProveedor", ReplyAction="http://tempuri.org/IService1/getProveedorResponse")]
        ServiceReference1.Proveedor getProveedor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProveedor", ReplyAction="http://tempuri.org/IService1/getProveedorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Proveedor> getProveedorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createProveedor", ReplyAction="http://tempuri.org/IService1/createProveedorResponse")]
        string createProveedor(ServiceReference1.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createProveedor", ReplyAction="http://tempuri.org/IService1/createProveedorResponse")]
        System.Threading.Tasks.Task<string> createProveedorAsync(ServiceReference1.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateProveedor", ReplyAction="http://tempuri.org/IService1/updateProveedorResponse")]
        string updateProveedor(ServiceReference1.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateProveedor", ReplyAction="http://tempuri.org/IService1/updateProveedorResponse")]
        System.Threading.Tasks.Task<string> updateProveedorAsync(ServiceReference1.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProveedor", ReplyAction="http://tempuri.org/IService1/deleteProveedorResponse")]
        string deleteProveedor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProveedor", ReplyAction="http://tempuri.org/IService1/deleteProveedorResponse")]
        System.Threading.Tasks.Task<string> deleteProveedorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProveedores", ReplyAction="http://tempuri.org/IService1/GetProveedoresResponse")]
        ServiceReference1.Proveedor[] GetProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProveedores", ReplyAction="http://tempuri.org/IService1/GetProveedoresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAlmacen", ReplyAction="http://tempuri.org/IService1/getAlmacenResponse")]
        ServiceReference1.Almacen getAlmacen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAlmacen", ReplyAction="http://tempuri.org/IService1/getAlmacenResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Almacen> getAlmacenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createAlmacen", ReplyAction="http://tempuri.org/IService1/createAlmacenResponse")]
        string createAlmacen(ServiceReference1.Almacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createAlmacen", ReplyAction="http://tempuri.org/IService1/createAlmacenResponse")]
        System.Threading.Tasks.Task<string> createAlmacenAsync(ServiceReference1.Almacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateAlmacen", ReplyAction="http://tempuri.org/IService1/updateAlmacenResponse")]
        string updateAlmacen(ServiceReference1.Almacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateAlmacen", ReplyAction="http://tempuri.org/IService1/updateAlmacenResponse")]
        System.Threading.Tasks.Task<string> updateAlmacenAsync(ServiceReference1.Almacen almacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteAlmacen", ReplyAction="http://tempuri.org/IService1/deleteAlmacenResponse")]
        string deleteAlmacen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteAlmacen", ReplyAction="http://tempuri.org/IService1/deleteAlmacenResponse")]
        System.Threading.Tasks.Task<string> deleteAlmacenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlmacenes", ReplyAction="http://tempuri.org/IService1/GetAlmacenesResponse")]
        ServiceReference1.Almacen[] GetAlmacenes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlmacenes", ReplyAction="http://tempuri.org/IService1/GetAlmacenesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Almacen[]> GetAlmacenesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducto", ReplyAction="http://tempuri.org/IService1/getProductoResponse")]
        ServiceReference1.Producto getProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducto", ReplyAction="http://tempuri.org/IService1/getProductoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Producto> getProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createProducto", ReplyAction="http://tempuri.org/IService1/createProductoResponse")]
        string createProducto(ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createProducto", ReplyAction="http://tempuri.org/IService1/createProductoResponse")]
        System.Threading.Tasks.Task<string> createProductoAsync(ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateProducto", ReplyAction="http://tempuri.org/IService1/updateProductoResponse")]
        string updateProducto(ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateProducto", ReplyAction="http://tempuri.org/IService1/updateProductoResponse")]
        System.Threading.Tasks.Task<string> updateProductoAsync(ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProducto", ReplyAction="http://tempuri.org/IService1/deleteProductoResponse")]
        string deleteProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProducto", ReplyAction="http://tempuri.org/IService1/deleteProductoResponse")]
        System.Threading.Tasks.Task<string> deleteProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        ServiceReference1.Producto[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Producto[]> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createRemisionEntrada", ReplyAction="http://tempuri.org/IService1/createRemisionEntradaResponse")]
        string createRemisionEntrada(ServiceReference1.RemisionEntrada remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/createRemisionEntrada", ReplyAction="http://tempuri.org/IService1/createRemisionEntradaResponse")]
        System.Threading.Tasks.Task<string> createRemisionEntradaAsync(ServiceReference1.RemisionEntrada remision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRemisiones", ReplyAction="http://tempuri.org/IService1/getRemisionesResponse")]
        ServiceReference1.RemisionEntrada[] getRemisiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRemisiones", ReplyAction="http://tempuri.org/IService1/getRemisionesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RemisionEntrada[]> getRemisionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateEstado", ReplyAction="http://tempuri.org/IService1/updateEstadoResponse")]
        string updateEstado(int idRemision, int accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateEstado", ReplyAction="http://tempuri.org/IService1/updateEstadoResponse")]
        System.Threading.Tasks.Task<string> updateEstadoAsync(int idRemision, int accion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.Proveedor getProveedor(int id)
        {
            return base.Channel.getProveedor(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Proveedor> getProveedorAsync(int id)
        {
            return base.Channel.getProveedorAsync(id);
        }
        
        public string createProveedor(ServiceReference1.Proveedor proveedor)
        {
            return base.Channel.createProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<string> createProveedorAsync(ServiceReference1.Proveedor proveedor)
        {
            return base.Channel.createProveedorAsync(proveedor);
        }
        
        public string updateProveedor(ServiceReference1.Proveedor proveedor)
        {
            return base.Channel.updateProveedor(proveedor);
        }
        
        public System.Threading.Tasks.Task<string> updateProveedorAsync(ServiceReference1.Proveedor proveedor)
        {
            return base.Channel.updateProveedorAsync(proveedor);
        }
        
        public string deleteProveedor(int id)
        {
            return base.Channel.deleteProveedor(id);
        }
        
        public System.Threading.Tasks.Task<string> deleteProveedorAsync(int id)
        {
            return base.Channel.deleteProveedorAsync(id);
        }
        
        public ServiceReference1.Proveedor[] GetProveedores()
        {
            return base.Channel.GetProveedores();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Proveedor[]> GetProveedoresAsync()
        {
            return base.Channel.GetProveedoresAsync();
        }
        
        public ServiceReference1.Almacen getAlmacen(int id)
        {
            return base.Channel.getAlmacen(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Almacen> getAlmacenAsync(int id)
        {
            return base.Channel.getAlmacenAsync(id);
        }
        
        public string createAlmacen(ServiceReference1.Almacen almacen)
        {
            return base.Channel.createAlmacen(almacen);
        }
        
        public System.Threading.Tasks.Task<string> createAlmacenAsync(ServiceReference1.Almacen almacen)
        {
            return base.Channel.createAlmacenAsync(almacen);
        }
        
        public string updateAlmacen(ServiceReference1.Almacen almacen)
        {
            return base.Channel.updateAlmacen(almacen);
        }
        
        public System.Threading.Tasks.Task<string> updateAlmacenAsync(ServiceReference1.Almacen almacen)
        {
            return base.Channel.updateAlmacenAsync(almacen);
        }
        
        public string deleteAlmacen(int id)
        {
            return base.Channel.deleteAlmacen(id);
        }
        
        public System.Threading.Tasks.Task<string> deleteAlmacenAsync(int id)
        {
            return base.Channel.deleteAlmacenAsync(id);
        }
        
        public ServiceReference1.Almacen[] GetAlmacenes()
        {
            return base.Channel.GetAlmacenes();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Almacen[]> GetAlmacenesAsync()
        {
            return base.Channel.GetAlmacenesAsync();
        }
        
        public ServiceReference1.Producto getProducto(int id)
        {
            return base.Channel.getProducto(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Producto> getProductoAsync(int id)
        {
            return base.Channel.getProductoAsync(id);
        }
        
        public string createProducto(ServiceReference1.Producto producto)
        {
            return base.Channel.createProducto(producto);
        }
        
        public System.Threading.Tasks.Task<string> createProductoAsync(ServiceReference1.Producto producto)
        {
            return base.Channel.createProductoAsync(producto);
        }
        
        public string updateProducto(ServiceReference1.Producto producto)
        {
            return base.Channel.updateProducto(producto);
        }
        
        public System.Threading.Tasks.Task<string> updateProductoAsync(ServiceReference1.Producto producto)
        {
            return base.Channel.updateProductoAsync(producto);
        }
        
        public string deleteProducto(int id)
        {
            return base.Channel.deleteProducto(id);
        }
        
        public System.Threading.Tasks.Task<string> deleteProductoAsync(int id)
        {
            return base.Channel.deleteProductoAsync(id);
        }
        
        public ServiceReference1.Producto[] GetProductos()
        {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Producto[]> GetProductosAsync()
        {
            return base.Channel.GetProductosAsync();
        }
        
        public string createRemisionEntrada(ServiceReference1.RemisionEntrada remision)
        {
            return base.Channel.createRemisionEntrada(remision);
        }
        
        public System.Threading.Tasks.Task<string> createRemisionEntradaAsync(ServiceReference1.RemisionEntrada remision)
        {
            return base.Channel.createRemisionEntradaAsync(remision);
        }
        
        public ServiceReference1.RemisionEntrada[] getRemisiones()
        {
            return base.Channel.getRemisiones();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemisionEntrada[]> getRemisionesAsync()
        {
            return base.Channel.getRemisionesAsync();
        }
        
        public string updateEstado(int idRemision, int accion)
        {
            return base.Channel.updateEstado(idRemision, accion);
        }
        
        public System.Threading.Tasks.Task<string> updateEstadoAsync(int idRemision, int accion)
        {
            return base.Channel.updateEstadoAsync(idRemision, accion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50084/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
